Прогресс 21.06
TheGodseeker/PR_timetracker pull request #3
Opened 2024-06-20 23:46 UTC by TheGodseeker

2024-06-24 05:59 UTC, AndreyGurev requested changes

2024-06-24 05:59 UTC, AndreyGurev commented on timetrackerUI/styles/styles.css
один файл со стилями - идея плохая. Представь, что твое приложение будет в 100 раз больше. Такой файл невозможно будет читать. 
Лучше делать файл стилей отдельно для каждой компоненты. 
Общие стили для всех лучше так и называть Shared или Common styles.

2024-06-24 05:59 UTC, AndreyGurev commented on timetracker/Controller.cs
Контроллеров в проекте обычно очень много, каждый отвечает за свою область. 
Этот твой, за задачи, поэтому так и назови его - TaskController

2024-06-24 05:59 UTC, AndreyGurev commented on timetracker/Controller.cs
> +
старайся не допускать таких помарок. Ниже у тебя 4 строки пустые. Это может усложнять чтение

2024-06-24 05:59 UTC, AndreyGurev commented on timetracker/Controller.cs
> +                    foreach(var task in context.tasks.ToList()){
Используй фильтры при запросе. Незачем доставать ВСЕ таски и фильтровать их в приложении.
Используй IQueryable. В данном случае подойдет Where

2024-06-24 05:59 UTC, AndreyGurev commented on timetracker/Controller.cs
> +                    string result = JsonSerializer.Serialize(tasks);
не указывай явно типы. Хотя некоторые и рекомендуют так делать, все таки это не очень хорошая практика в современном мире - код становится громоздким, ухудшается читабельность. 
тем более, выше ты используешь var. Либо var либо точные типы

2024-06-24 05:59 UTC, AndreyGurev commented on timetracker/Controller.cs
> +                    foreach(var task in context.tasks.ToList()){
тоже самое, используй фильтры запросов

2024-06-24 05:59 UTC, AndreyGurev commented on timetracker/Controller.cs
> +            public void AddTask(string _name, string _desc = null, long exptTime = 0)
подчерки "_" используются для приватных полей и свойств, не для параметров

2024-06-24 05:59 UTC, AndreyGurev commented on timetracker/Controller.cs
> +                using (var context = new DBConnector()){
using можно использовать без {}, так ты избегаешь вложенности.
Используй var using

2024-06-24 05:59 UTC, AndreyGurev commented on timetracker/Controller.cs
Тебе нужно разнести логику работы с тасками и логику в контроллере. Писанины будет больше, но поддерживаемость  кода улучшиться. Начни хотя бы с репозитория. 
https://habr.com/ru/articles/248505/

2024-06-24 05:59 UTC, AndreyGurev commented on timetracker/Controller.cs
> +                using (var context = new DBConnector()){
Используй DI. https://metanit.com/sharp/aspnet5/6.1.php
Так тебе не придется каждый раз объявлять DBConnector в методах, ты просто передаешь его в конструктор

2024-06-24 05:59 UTC, AndreyGurev commented on timetracker/Controller.cs
> +            TO-DO:
Молодец! Такие тудухи хорошая практика - позволяет не забыть важные вещи тебе и остальным участникам проекта

2024-06-24 05:59 UTC, AndreyGurev commented on timetracker/Controller.cs
> +                    if (curGap != null)
а если curGap  == null? какую ошибку получить клиент?
Лучше обрабатывать такие частные случаи внятными ошибками.

2024-06-24 23:57 UTC, TheGodseeker commented on timetracker/Controller.cs
> +
Поправил

2024-06-25 00:54 UTC, TheGodseeker commented on timetracker/Controller.cs
> +                    if (curGap != null)
Сделал. Теперь функция возвращает IActionResult: пустой "Ok", если все прошло успешно, и "NoContent", если что-то пошло не так

2024-06-25 00:55 UTC, TheGodseeker commented on timetracker/Controller.cs
> +                using (var context = new DBConnector()){
Сделано

2024-06-25 01:11 UTC, TheGodseeker commented on timetracker/Controller.cs
> +                    foreach(var task in context.tasks.ToList()){
Сделано

2024-06-25 01:12 UTC, TheGodseeker commented on timetracker/Controller.cs
> +                    foreach(var task in context.tasks.ToList()){
Сделано

2024-06-25 01:14 UTC, TheGodseeker commented on timetracker/Controller.cs
Разделил на два отдельных контроллера: для задач и для промежутков времени.

2024-06-27 23:48 UTC, TheGodseeker commented on timetracker/Controller.cs
Сделано

2024-06-27 23:49 UTC, TheGodseeker commented on timetracker/Controller.cs
> +                using (var context = new DBConnector()){
Сделано

2024-06-28 00:48 UTC, merged